spring.application.name=neurowiki-backend

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/neurowikidb}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Multipart File Upload Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration
jwt.secret=${JWT_SECRET:neurowiki_super_secret_jwt_key_which_is_at_least_256_bits_long_for_hs256_security_token!}
jwt.expiration=${JWT_EXPIRATION:86400000}



# AI Provider Configuration
ai.api.key=AQ.Ab8RN6KwQZmBCMU2gMEGhjBcfzn-isJyE1b0yQmcSsaxl6vh5w
ai.model=${AI_MODEL:gemini-3.5-flash}
ai.base.url=${AI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
embedding.model=${EMBEDDING_MODEL:gemini-embedding-001}

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.neurowiki=INFO
